services:
  dsatrek-1:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 3G
        reservations:
          cpus: '0.4'
          memory: 1.5G

  dsatrek-2:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 2G
        reservations:
          cpus: '0.3'
          memory: 1G

  nginx:
    image: nginx:1.29.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 512M