services:
  dsatrek:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsatrek-app
    ports:
      - '3000'
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://dsatrek.com
      - PORT=3000
    env_file:
      - .env.production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 1G
          cpus: '0.5'

    networks:
      - dsatrek-network

  nginx:
    image: nginx:alpine
    container_name: dsatrek-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - dsatrek
    restart: unless-stopped
    networks:
      - dsatrek-network

networks:
  dsatrek-network:
    driver: bridge
